---
deployment:
  tasks:
    - export DEPLOYPATH=/home/chaitanya/public_html/desiccants
    - /bin/cp * $DEPLOYPATH
    - /bin/cp img/* $DEPLOYPATH
    - /bin/cp css/* $DEPLOYPATH
    - /bin/cp js/* $DEPLOYPATH
