---
deployment:
  tasks:
    - export DEPLOYPATH=/home/chaitanya/public_html/desiccants/
    - /bin/cp * $DEPLOYPATH
    - /bin/cp -R /img $DEPLOYPATH
    - /bin/cp -R /css $DEPLOYPATH
    - /bin/cp -R /js $DEPLOYPATH